export const theme = {
  breakpoints: ["32rem", "48rem", "64rem", "75rem"],
  space: [
    0,
    4,
    8,
    12,
    16,
    20,
    24,
    28,
    32,
    36,
    40,
    44,
    48,
    52,
    56,
    60,
    64,
    72,
    80,
    88,
    96,
  ],
  fontSize: [12, 14, 16, 20, 24, 32, 36, 48, 64],
  colors: {
    white: "#FFFFFF",
    offWhite: "#f3f4f4",
    yellow: "#eaff2d",
    pink: "#ffa5db",
  },
  fonts: {
    body: `'Roboto', sans-serif`,
    heading: `'VCR OSD Mono', sans-serif;`,
    monospace: "VCR OSD Mono, monospace",
  },
  text: {
    heading1: {},
    heading2: {
      fontSize: [4, null, "36px"],
      lineHeight: 1.2,
      color: "pink",
      fontWeight: 400,
      textTransform: "uppercase",
    },
    paragraph: {
      fontFamily: "body",
      color: "white",
      fontSize: [5],
    },
  },
  buttons: {
    primary: {
      cursor: "pointer",
      color: "black",
      textTransform: "uppercase",
      fontWeight: "bold",
      minWidth: 150,
      paddingTop: "14px",
      paddingBottom: "14px",
      "&:hover": {
        backgroundColor: "#AAA",
        color: "white",
      },
    },
  },
  forms: {
    input: {
      fontFamily: "heading",
      padding: "14px 32px 14px 16px",
      backgroundColor: "#fff",
      color: "black",
      fontSize: "20px",

      "&:focus": {
        outline: "3px solid #AAA",
        outlineOffset: 0,
      },
    },
    textarea: {
      fontFamily: "heading",
      padding: "14px 32px 14px 16px",
      backgroundColor: "#fff",
      color: "black",
      fontSize: "20px",

      "&:focus": {
        outline: "3px solid #AAA",
        outlineOffset: 0,
      },
    },
    label: {
      fontWeight: "bold",
      marginBottom: 2,
      fontSize: 1,
    },
    radio: {},
    checkbox: {},
  },
}
