export const theme = {
  breakpoints: ["32rem", "48rem", "64rem", "75rem"],
  space: [
    0,
    4,
    8,
    12,
    16,
    20,
    24,
    28,
    32,
    36,
    40,
    44,
    48,
    52,
    56,
    60,
    64,
    72,
    80,
    88,
    96,
  ],
  fontSize: [12, 14, 16, 20, 24, 32, 36, 48, 64],
  colors: {
    white: "#FFFFFF",
    offWhite: "#f3f4f4",
    yellow: "#eaff2d",
    pink: "#ffa5db",
  },
  fonts: {
    body: `'vcr_osd_monoregular', sans-serif`,
    heading: `'vcr_osd_monoregular', sans-serif;`,
    monospace: "vcr_osd_monoregular, monospace",
  },
  forms: {
    input: {
      fontFamily: "heading",
      padding: "14px 32px 14px 16px",
      boxShadow: "inset 4px 4px 0 #DDD",
      border: "2px solid #333",
      "&:focus": {
        outline: "3px solid #AAA",
        outlineOffset: 0,
      },
    },
    select: {
      fontFamily: "heading",
      padding: "14px 32px 14px 16px",
      boxShadow: "inset 4px 4px 0 #DDD",
      border: "2px solid #333",
      "&:focus": {
        outline: "3px solid #AAA",
        outlineOffset: 0,
      },
    },
    textarea: {},
    label: {
      fontWeight: "bold",
      marginBottom: 2,
      fontSize: 1,
    },
    radio: {},
    checkbox: {},
  },
}
